export { default as Sidebar } from "./SideBar"
export { default as UserProfile } from "./UserProfile"
export { default as Loigin } from "./Login"
export { default as Navbar } from "./Navbar"
export { default as Feed } from "./Feed"
export { default as CreatePin } from "./CreatePin"
export { default as Search } from "./Search"
export { default as PinDetail } from "./PinDetail"